<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <Version>0.0.0.7</Version>
        <Description>A time-saving plugin.</Description>
        <PackageProjectUrl>https://github.com/oorzkws/QuickRelist</PackageProjectUrl>
        <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
        <IsPackable>false</IsPackable>
        <RootNamespace>QuickRelist</RootNamespace>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Platforms>x64</Platforms>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <OutputPath>bin\$(Configuration)\</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ECommons" Version="3.2.0.3" />
        <PackageReference Include="Krafs.Publicizer" Version="2.2.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <Publicize Include="Dalamud:Dalamud.Game.Network"/>
        <Publicize Include="Dalamud:Dalamud.Game.Network.Internal.NetworkHandlersAddressResolver"/>
        <Publicize Include="Dalamud:Dalamud.Game.Network.Internal.NetworkHandlers"/>
        <Publicize Include="Dalamud:Dalamud.Game.Network.Internal.MarketBoardUploaders"/>
        <Publicize Include="Dalamud:Dalamud.Game.Network.Internal.MarketBoardUploaders.MarketBoardItemRequest"/>
        <Publicize Include="Dalamud:Dalamud.Game.Network.Internal.MarketBoardUploaders.MarketBoardItemRequest..ctor"/>
        <Publicize Include="Dalamud:Dalamud.Game.Network.Internal.MarketBoardUploaders.MarketBoardItemRequest.Read"/>
        <PackageReference Update="DalamudPackager" Version="15.0.0" />
        <PackageReference Update="DotNet.ReproducibleBuilds" Version="1.2.39" />
    </ItemGroup>
    <PropertyGroup>
        <PublicizerClearCacheOnClean>true</PublicizerClearCacheOnClean>
    </PropertyGroup>
</Project>
