<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/13.0.0">
    <PropertyGroup>
        <Version>0.0.0.3</Version>
        <Description>A time-saving plugin.</Description>
        <PackageProjectUrl>https://github.com/oorzkws/QuickRelist</PackageProjectUrl>
        <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
        <IsPackable>false</IsPackable>
        <RootNamespace>QuickRelist</RootNamespace>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Platforms>x64</Platforms>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <OutputPath>bin\$(Configuration)\</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ECommons\ECommons\ECommons.csproj"/>
    </ItemGroup>
    
    <!-- Until Dalamud release-->
    <PropertyGroup>
        <DalamudLibPath>D:\Utilities\DalamudStandalone\Dalamud\bin\Release\</DalamudLibPath>
    </PropertyGroup>
    <ItemGroup>
        <Reference Include="Dalamud.Bindings.ImGui">
            <HintPath>$(DalamudLibPath)Dalamud.Bindings.ImGui.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Krafs.Publicizer" Version="2.2.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <Publicize Include="Dalamud:Dalamud.Game.Network"/>
        <Publicize Include="Dalamud:Dalamud.Game.Network.Internal.NetworkHandlersAddressResolver"/>
        <Publicize Include="Dalamud:Dalamud.Game.Network.Internal.NetworkHandlers"/>
        <Publicize Include="Dalamud:Dalamud.Game.Network.Internal.MarketBoardUploaders"/>
        <Publicize Include="Dalamud:Dalamud.Game.Network.Internal.MarketBoardUploaders.MarketBoardItemRequest"/>
        <Publicize Include="Dalamud:Dalamud.Game.Network.Internal.MarketBoardUploaders.MarketBoardItemRequest..ctor"/>
        <Publicize Include="Dalamud:Dalamud.Game.Network.Internal.MarketBoardUploaders.MarketBoardItemRequest.Read"/>
    </ItemGroup>
    <PropertyGroup>
        <PublicizerClearCacheOnClean>true</PublicizerClearCacheOnClean>
    </PropertyGroup>
</Project>
